# file: apt/tasks/main.yml

- name: APT | Reset the sources list (/etc/apt/sources.list)
  copy:
    src: etc_apt_sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  when: apt_reset_source_list

- name: APT | Update the apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time}}"

- name: APT | Remove packages that are no longer needed for dependencies
  shell: apt-get -y autoremove
  when: apt_autoremove

- name: APT | Remove .deb files for packages no longer on your system
  shell: apt-get -y autoclean
  when: apt_autoclean

- name: APT | Update the general configuration (/etc/apt/apt.conf.ds/10general)
  template:
    src: etc_apt_apt.conf.d_10general.j2
    dest: /etc/apt/apt.conf.d/10general
    owner: root
    group: root
    mode: 0644

- name: APT | Make sure the required packages are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - python-apt
    - unattended-upgrades
